version: "3"

services: 
  chat: 
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app 
      - /app/node_modules 
      - /files
  redis:
    image: redis:latest 
    volumes:
      - /data 
    ports:
      - 6379
    command: redis-server --appendonly yes  